config/routes.rb
Rails.application.routes.draw do
  get 'studios/index'


  get "/signup", to: "users#new", as: "new_user"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  root 'studios#index'

  resources :users, only: [:index, :create, :show]

  resources :spin_classes, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:index, :new, :create, :show]
  end
  resources :studios, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :spin_class
  validates :guests, :numericality => { :greater_than_or_equal_to => 0 }
  validates_presence_of :spin_class_id
  scope :without_guests, -> { where(guests: 0) }
  scope :with_guests, -> { where.not(guests: 0) }
end

app/models/spin_class.rb
# frozen_string_literal: true

class SpinClass < ApplicationRecord
  belongs_to :studio
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations
  validates :name, presence: true

  def attendees
    reservations.sum(:guests)
  end
end

app/models/studio.rb
# frozen_string_literal: true

class Studio < ApplicationRecord
  has_many :users
  has_many :spin_classes
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :reservations
  has_many :spin_classes, through: :reservations
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    session[:user_id] ? true : false
  end

  def authorize
    return if logged_in? == true

    redirect_to signin_path, alert: "You must be logged in to view this page."
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true
class ReservationsController < ApplicationController
  before_action :authorize

  def index
    @spin_class = SpinClass.find(params[:spin_class_id])
    @reservations = @spin_class.reservations
    # binding.pry
    respond_to do |format|
      format.html {render :index}
      format.json do
        render json: @reservations.to_json(include: :user)
      end
    end
  end

  def new
    @spin_class = SpinClass.find(params[:spin_class_id])
    @reservation = Reservation.new
  end

  def show
    @reservation = current_user.reservations.find_by(
      id: params[:id]
    )
    # render :json => @reservations
  end

  def create
    @spin_class = SpinClass.find(params[:spin_class_id])
    @reservation = @spin_class.reservations.new(reservation_params)
    @reservation.user = current_user

    if @reservation.save
      redirect_to spin_class_path(@spin_class)
    else
      flash.now.alert = "Something went wrong, please try again"
      render new_spin_class_reservation_path(@spin_class)
    end
  end

private

  def reservation_params
    params.require(:reservation).permit(
      :guests,
      :spin_class_id,
      :user_id
    )
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:signin][:email])
    if user&.authenticate(params[:signin][:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Successfully logged in!"
    else
      unsuccessful_login
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to signin_path, notice: "Successfully logged out!"
  end

private

  def unsuccessful_login
    flash.now.alert = "Incorrect email or password, please try again."
    render :new
  end
end

app/controllers/spin_classes_controller.rb
# frozen_string_literal: true

class SpinClassesController < ApplicationController
  def index
    @studios = Studio.all
    @spin_class = SpinClass.new

  end

  def new
    @spin_class = SpinClass.new
  end

  def show
    @spin_class = SpinClass.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        render json: @spin_class.to_json(:only => [ :instructor ])
      end
    end
  end

  def create
    @spin_class = SpinClass.new(spin_class_params)
    if @spin_class.save
      render json: @spin_class.to_json
    end
  end

private

  def spin_class_params
    params.require(:spin_class).permit(
      :name,
      :studio_id,
      :instructor
    )
  end
end

app/controllers/studios_controller.rb
# frozen_string_literal: true

class StudiosController < ApplicationController
  def index
    @studios = Studio.all
  end

  def show
    @studio = Studio.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authorize, only: %i[show index]

  def index; end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id]) if params[:id].to_i == current_user.id
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Account created successfully!"
    else
      flash.now[:alert] = "Could not create account. " \
      "Try again."
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password
    )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpinStudio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <% if current_user %>
      <%= link_to('Logout', logout_path, method: :delete) %>
    <% else %>
      <%= link_to('Login', signin_path) %>
      <%= link_to('Sign Up', new_user_path) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h4>With Guests</h4>
 <ol class="list-group">
    <% @reservations.with_guests.each do |reservation| %>
    <li class="list-group-item"><%= reservation.user.name %> Guest count: <%= reservation.guests %></li>
     <% end %>
   </ol>


<h4>Without Guests</h4>
  <ol class="list-group">
    <% @reservations.without_guests.each do |reservation| %>
      <li class="list-group-item"><%= reservation.user.name %></li>
      <% end %>
    </ol>
</div>
<%= link_to "Back", user_path(current_user), role: "button", class: "btn btn-primary btn-sm" %>

app/views/reservations/new.html.erb
<h2>New Reservation For: <%= @spin_class.name %></h2>
  <%= form_for [@spin_class, @reservation] do |f| %>
  <div class="form-group">
    <%= f.label :guests %>
    <%= f.number_field :guests %>
  </div>
  <%= f.submit "Join Class", class: "btn btn-primary btn-sm"%></br>
  <%= link_to('Back', spin_classes_path) %>
  <% end %>

app/views/spin_classes/index.html.erb
<h2>All Spin Classes</h2>
<h4>Click to join a class:</h4>
<ul class="list-group">
  <% @studios.each do |studio| %>
  <h4>Spin Classes for Studio
    <%= link_to studio.name, studio_path(studio) %>
  </h4>
  <ul id="studio_<%= studio.id %>_spin_classes">
  <% studio.spin_classes.each do |spin_class| %>
    <li class="list-group-item"><%= spin_class.name %>

      <% if Reservation.find_by(user: current_user, spin_class: spin_class).nil? %>
        <%= link_to "Join", new_spin_class_reservation_path(spin_class) %>
      <% else %>

      <h6>Number of Attendees: <%= spin_class.attendees %></h6>
      <h6>Instructor: <%= spin_class.instructor %></h6>
        <h6>You've already joined this spin class!</h6>
      <% end %>
    </li>
      <% end %>
    </ul>

      <% end %>

      <%= form_for (@spin_class) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.collection_select :studio_id, Studio.all, :id, :name %>
        <p><%= f.submit "Create Class", class: "btn btn-primary btn-sm"%></p>
  <% end %>

</ul>

<%= javascript_include_tag "spin_class_form.js" %>

app/views/spin_classes/new.html.erb
<%= form_for @spin_class do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.collection_select :studio_id, Studio.all, :id, :name %>
  </div>
  <%= f.submit "Create Class", class: "btn btn-primary btn-sm"%></br>
  <%= link_to('Back', spin_classes_path) %>
<% end %>

app/views/spin_classes/show.html.erb
<h2>You have joined a class!</h2>
<h4> <%= @spin_class.name %></h4>
<h5>List of all attendees:</h5>
<ol>
<% @spin_class.users.each do |user| %>
 <li><%= user.name %></li>
  <% end %>
</ol>

<p>
<%= link_to "Attending Guests", spin_class_reservations_path(@spin_class), class: "attending_guests" %>
</p>
<div class="guests">

</div>

<%= link_to('Back', spin_classes_path) %>

app/views/studios/index.html.erb
<h2>Welcome to SpinSpin Studio!</h2>
<h4>If previous member please login:</h4>

<div class="container">
 <%= link_to 'User Login', signin_path %>
 <br>

<h4>New members please signup below:</h4>
 <%= link_to 'User Signup', new_user_path(@user) %>
</div>

app/views/studios/show.html.erb
<div class="container">
  <div class="col">
    <h4> <%= @studio.name %></h4>

  <ol>
    <% @studio.spin_classes.each do |spin_class| %>
      <li><%= link_to(spin_class.name, spin_class_path(spin_class), class: "spin_class") %></li>
    <% end %>
  </ol>

    <div class="spin_class">

    </div>
    </div>
  </div>
</div>

<%= link_to('Back', spin_classes_path) %>

<%= javascript_include_tag "instructor_listener.js" %>

app/views/users/index.html.erb
<h1>Thank You Signing Up</h1>

app/views/users/new.html.erb
<div class="container">
  <h2>Create Your Spin Class Membership!</h2>
  <br>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, required: true %>
    </div>
    <%= f.submit "Create account!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col">
    <h2><%= @user.name %>'s account</h2>
    <h3>Click to view the classes available:</h3>
  </div>
  <div class="col">
    <%= link_to "View all Spin Classes", spin_classes_path %>
  </div>
</div>